formula_one:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'HITESH') }}"
      threads: 2
      client_session_keep_alive: false
      query_tag: "formula1_local_dbt"
      connect_retries: 1
      connect_timeout: 20
      retry_on_database_errors: false
      retry_all: false
      reuse_connections: true
