apiVersion: 1

datasources:
  - name: SingleStore Realtime
    uid: singlestore_realtime
    type: mysql
    access: proxy
    url: singlestore:3306
    user: root
    database: f1_realtime
    isDefault: true
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    secureJsonData:
      password: ${SINGLESTORE_ROOT_PASSWORD}
